on:
  push:
    branches: master
    paths:
      - 'vignettes/**'
      - 'man/**'
      - 'README.**'
  schedule:
  # Rerun pkgdown after the (expected) time package is rebuilt on the daily.
  # Let's give it 30 mins
  - cron: '30 12 * * *'

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: facilebio/facilebio_base_extra
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GIT_AUTHOR_NAME: Steve Lianoglou
      GIT_AUTHOR_EMAIL: slianoglou@gmail.com
      GIT_COMMITTER_NAME: Steve Lianoglou
      GIT_COMMITTER_EMAIL: slianoglou@gmail.com

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: remotes::install_deps(dependencies = TRUE, upgrade = FALSE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Build pkgdown site and deploy
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
